=== ikagil25-coder/5.Erronka_Ozerova/xml/donazioak.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="IzenMota">
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
            <xs:maxLength value="150"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ifkMota">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Za-z][0-9]{8}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="motaMota">
        <xs:restriction base="xs:string">
            <xs:enumeration value="iragankorra"/>
            <xs:enumeration value="ez iragankorra"/>
            <xs:enumeration value="erdi iragankorra"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="baiEzMota">
        <xs:restriction base="xs:string">
            <xs:enumeration value="BAI"/>
            <xs:enumeration value="EZ"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="erreferentziaMota">
        <xs:restriction base="xs:string">
            <xs:pattern value="(IR|EZ|EI)[0-9]{5}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:element name="donazioak">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="donazioa" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="enpresa_emailea">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ifk" type="ifkMota"/>
                                        <xs:element name="izena" type="IzenMota"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="data" type="xs:date"/>
                            <xs:element name="elikagaiak">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="elikagaia" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="mota" type="motaMota"/>
                                                    <xs:element name="erreferentzia" type="erreferentziaMota"/>
                                                    <xs:element name="produktu_izena" type="IzenMota"/>
                                                    <xs:element name="kopurua" type="xs:positiveInteger"/>
                                                    <xs:element name="ekoizlea" type="IzenMota"/>
                                                    <xs:element name="iraungitze_data" type="xs:date" minOccurs="0"/>
                                                    <xs:element name="hoztuta_mantendu" type="baiEzMota" minOccurs="0"/>
                                                    <xs:element name="kontserba" type="baiEzMota" minOccurs="0"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== ikagil25-coder/5.Erronka_Ozerova/xml/donazioak.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="donazioak.xsl" ?>
<donazioak xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="donazioak.xsd">
    <donazioa>
        <enpresa_emailea>
            <ifk>A12345678</ifk>
            <izena>Esnekiak Araba S.L.</izena>
        </enpresa_emailea>
        <data>2026-03-20</data>
        <elikagaiak>
            <elikagaia>
                <mota>iragankorra</mota>
                <erreferentzia>IR10293</erreferentzia>
                <produktu_izena>Behi esne osoa</produktu_izena>
                <kopurua>500</kopurua>
                <ekoizlea>Iparraldeko Esnekiak</ekoizlea>
                <iraungitze_data>2026-04-15</iraungitze_data>
                <hoztuta_mantendu>BAI</hoztuta_mantendu>
            </elikagaia>
        </elikagaiak>
    </donazioa>

    <donazioa>
        <enpresa_emailea>
            <ifk>B98765432</ifk>
            <izena>Gure Laborea Taldea</izena>
        </enpresa_emailea>
        <data>2026-03-21</data>
        <elikagaiak>
            <elikagaia>
                <mota>ez iragankorra</mota>
                <erreferentzia>EZ55443</erreferentzia>
                <produktu_izena>Arroz borobila 1kg</produktu_izena>
                <kopurua>1200</kopurua>
                <ekoizlea>Erriberako Arroz-soroak</ekoizlea>
                <kontserba>EZ</kontserba>
            </elikagaia>
        </elikagaiak>
    </donazioa>

    <donazioa>
        <enpresa_emailea>
            <ifk>C45678901</ifk>
            <izena>Baratze Berria Koop.</izena>
        </enpresa_emailea>
        <data>2026-03-22</data>
        <elikagaiak>
            <elikagaia>
                <mota>erdi iragankorra</mota>
                <erreferentzia>EI88127</erreferentzia>
                <produktu_izena>Patata poltsa 5kg</produktu_izena>
                <kopurua>300</kopurua>
                <ekoizlea>Nekazari Elkartea</ekoizlea>
            </elikagaia>
        </elikagaiak>
    </donazioa>
</donazioak>
